apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-backend-deployment
  labels:
    app: todolist-backend
spec:
  selector:
    matchLabels:
      app: todolist-backend
  template:
    metadata:
      labels:
        app: todolist-backend
    spec:
      containers:
      - name: todolist-backend-container
        image: localhost:5000/todolist-backend:0.0.1-SNAPSHOT-dev
        ports:
        - containerPort: 3001
--- 
apiVersion: v1
kind: Service
metadata:
  name: todolist-backend-service
spec:
  selector:
    app: todolist-backend
  ports:
  - protocol: TCP
    port: 3001
---
apiVersion: v1
kind: Route
metadata:
  name: todolist-backend-route
spec:
  to:
    kind: Service
    name: todolist-backend-service
