apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-frontend-deployment
  labels:
    app: todolist-frontend
spec:
  selector:
    matchLabels:
      app: todolist-frontend
  template:
    metadata:
      labels:
        app: todolist-frontend
    spec:
      containers:
      - name: todolist-frontend-container
        image: localhost:5000/todolist-frontend:0.0.1-SNAPSHOT-dev
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: todolist-frontend-service
spec:
  selector:
    app: todolist-frontend
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Route
metadata:
  name: todolist-frontend-route
spec:
  to:
    kind: Service
    name: todolist-frontend-service
